import { Language } from '../types';

type TranslationStructure = {
  splash: {
    question: string;
    subtext: string;
    enter: string;
  };
  language: {
    select: string;
    english: string;
    chinese: string;
    spanish: string;
    french: string;
    japanese: string;
    korean: string;
  };
  auth: {
    login: string;
    logout: string;
    loggingIn: string;
  };
  profile: {
    setupTitle: string;
    setupDescription: string;
    namePlaceholder: string;
    save: string;
    saving: string;
  };
  nav: {
    bountyBoard: string;
    launchMission: string;
    disputeResolution: string;
    personalCenter: string;
  };
  bountyBoard: {
    title: string;
    allQuests: string;
    noQuests: string;
    hype: string;
    contributors: string;
    acceptSuccess: string;
    acceptError: string;
    yourQuest: string;
    addToPot: string;
    addToPotDescription: string;
    currentPool: string;
    yourContribution: string;
    newPool: string;
    contribute: string;
    contributionSuccess: string;
    contributionError: string;
  };
  difficulty: {
    easy: string;
    medium: string;
    hard: string;
    extreme: string;
    impossible: string;
  };
  deposit: {
    required: string;
    acceptAndPayDeposit: string;
    confirmTitle: string;
    confirmDescription: string;
    questTitle: string;
    rewardPool: string;
    yourDepositRate: string;
    depositRequired: string;
    depositInfo: string;
    cancel: string;
    confirmAndPay: string;
    processing: string;
    transferFailed: string;
  };
  launchMission: {
    title: string;
    subtitle: string;
    questTitle: string;
    titlePlaceholder: string;
    rules: string;
    rulesPlaceholder: string;
    rewardPool: string;
    rewardHint: string;
    difficulty: string;
    createQuest: string;
    creating: string;
    fillAllFields: string;
    invalidReward: string;
    createSuccess: string;
    createError: string;
    titleRequired: string;
    descriptionTooShort: string;
    minCharacters: string;
  };
  creditScore: {
    title: string;
    depositRate: string;
    successfulQuests: string;
    totalEarned: string;
    totalDeposited: string;
    questsToMinimum: string;
    rateDecrease: string;
  };
  personalCenter: {
    title: string;
    subtitle: string;
    acceptedQuests: string;
    postedBounties: string;
    noAcceptedQuests: string;
    noPostedBounties: string;
    progress: string;
    status: string;
    reward: string;
    lockedDeposit: string;
    rewardPool: string;
    hypeCount: string;
    warrior: string;
    checkIn: string;
    viewProgress: string;
    deleteQuest: string;
    exitQuest: string;
    abandonQuest: string;
    statusActive: string;
    statusInProgress: string;
    statusPending: string;
    statusCompleted: string;
    statusDisputed: string;
    statusCancelled: string;
  };
  deleteQuest: {
    title: string;
    description: string;
    warning: string;
    cancel: string;
    confirm: string;
    deleting: string;
  };
  exitQuest: {
    title: string;
    description: string;
    yourContribution: string;
    crowdfunding: string;
    contributors: string;
    refundInfo: string;
    cancel: string;
    confirm: string;
    exiting: string;
  };
  abandonQuest: {
    title: string;
    description: string;
    forfeitAmount: string;
    depositRateReset: string;
    warning: string;
    typeConfirm: string;
    typeConfirmHint: string;
    cancel: string;
    confirm: string;
    abandoning: string;
  };
  dailyCheckIn: {
    title: string;
    day: string;
    description: string;
    firstDayNote: string;
    progress: string;
    target: string;
    days: string;
    statusUpdate: string;
    statusPlaceholder: string;
    photo: string;
    uploadPhoto: string;
    photoOptional: string;
    uploading: string;
    submit: string;
    submitting: string;
    requireContent: string;
    submitSuccess: string;
    submitError: string;
    fileTooLarge: string;
  };
  visualComparison: {
    title: string;
    day: string;
    totalCheckIns: string;
    timeline: string;
    autoGenerated: string;
  };
  disputeResolution: {
    title: string;
    subtitle: string;
    noDisputes: string;
    questTitle: string;
    publisher: string;
    warrior: string;
    publisherArgument: string;
    warriorArgument: string;
    voteDistribution: string;
    publisherVotes: string;
    adminVotes: string;
    communityVotes: string;
    voteForPublisher: string;
    voteForWarrior: string;
    votingClosed: string;
  };
  appealSubmission: {
    title: string;
    description: string;
    yourArgument: string;
    argumentPlaceholder: string;
    minCharacters: string;
    submit: string;
    submitting: string;
    argumentTooShort: string;
    submitSuccess: string;
    submitError: string;
    viewAppeal: string;
    yourAppeal: string;
    noAppeal: string;
  };
  footer: {
    builtWith: string;
    love: string;
    using: string;
  };
};

// Base English translations
const englishTranslations: TranslationStructure = {
  splash: {
    question: 'Will persistence make you stronger, or is it meaningless?',
    subtext: 'If "what if" became reality, would you truly be better?',
    enter: 'ENTER',
  },
  language: {
    select: 'Select Your Language',
    english: 'English',
    chinese: 'Chinese',
    spanish: 'Spanish',
    french: 'French',
    japanese: 'Japanese',
    korean: 'Korean',
  },
  auth: {
    login: 'Login',
    logout: 'Logout',
    loggingIn: 'Logging in...',
  },
  profile: {
    setupTitle: 'Welcome, Warrior',
    setupDescription: 'Enter your name to begin your journey',
    namePlaceholder: 'Your name',
    save: 'Save',
    saving: 'Saving...',
  },
  nav: {
    bountyBoard: 'Bounty Board',
    launchMission: 'Launch Mission',
    disputeResolution: 'Dispute Resolution',
    personalCenter: 'Personal Center',
  },
  bountyBoard: {
    title: 'Bounty Board',
    allQuests: 'All Quests',
    noQuests: 'No quests available',
    hype: 'Hype',
    contributors: 'contributors',
    acceptSuccess: 'Quest accepted successfully!',
    acceptError: 'Failed to accept quest',
    yourQuest: 'Your Quest',
    addToPot: 'Add to Pot',
    addToPotDescription: 'Increase the reward pool to attract more warriors',
    currentPool: 'Current Pool',
    yourContribution: 'Your Contribution',
    newPool: 'New Pool',
    contribute: 'Contribute',
    contributionSuccess: 'Contribution added successfully!',
    contributionError: 'Failed to add contribution',
  },
  difficulty: {
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    extreme: 'Extreme',
    impossible: 'Impossible',
  },
  deposit: {
    required: 'Deposit Required',
    acceptAndPayDeposit: 'Accept & Pay Deposit',
    confirmTitle: 'Confirm Deposit',
    confirmDescription: 'Lock your deposit to accept this quest',
    questTitle: 'Quest',
    rewardPool: 'Reward Pool',
    yourDepositRate: 'Your Deposit Rate',
    depositRequired: 'Deposit Required',
    depositInfo: 'Your deposit will be locked until quest completion. Complete successfully to earn rewards and reduce your deposit rate.',
    cancel: 'Cancel',
    confirmAndPay: 'Confirm & Pay',
    processing: 'Processing...',
    transferFailed: 'Transfer failed',
  },
  launchMission: {
    title: 'Launch Mission',
    subtitle: 'Create a new quest and set the challenge',
    questTitle: 'Quest Title',
    titlePlaceholder: 'e.g., Wake up at 5 AM for 100 days',
    rules: 'Quest Rules & Description',
    rulesPlaceholder: 'Describe the quest requirements and rules...',
    rewardPool: 'Initial Reward Pool (ICP)',
    rewardHint: 'Minimum 0.0001 ICP',
    difficulty: 'Difficulty Level',
    createQuest: 'Create Quest',
    creating: 'Creating...',
    fillAllFields: 'Please fill in all fields',
    invalidReward: 'Please enter a valid reward amount',
    createSuccess: 'Quest created successfully!',
    createError: 'Failed to create quest',
    titleRequired: 'Quest title is required',
    descriptionTooShort: 'Description must be at least 20 characters',
    minCharacters: 'characters minimum',
  },
  creditScore: {
    title: 'Warrior Credit Score',
    depositRate: 'Current Deposit Rate',
    successfulQuests: 'Successful Quests',
    totalEarned: 'Total Earned',
    totalDeposited: 'Total Deposited',
    questsToMinimum: 'quests to minimum rate (2%)',
    rateDecrease: 'Each success: -3%',
  },
  personalCenter: {
    title: 'Personal Center',
    subtitle: 'Track your quests and progress',
    acceptedQuests: 'Accepted Quests',
    postedBounties: 'Posted Bounties',
    noAcceptedQuests: 'No accepted quests yet',
    noPostedBounties: 'No posted bounties yet',
    progress: 'Progress',
    status: 'Status',
    reward: 'Reward',
    lockedDeposit: 'Locked Deposit',
    rewardPool: 'Reward Pool',
    hypeCount: 'Hype Count',
    warrior: 'Warrior',
    checkIn: 'Check In',
    viewProgress: 'View Progress',
    deleteQuest: 'Delete',
    exitQuest: 'Exit',
    abandonQuest: 'Abandon Quest',
    statusActive: 'Active',
    statusInProgress: 'In Progress',
    statusPending: 'Pending',
    statusCompleted: 'Completed',
    statusDisputed: 'Disputed',
    statusCancelled: 'Cancelled',
  },
  deleteQuest: {
    title: 'Delete Quest',
    description: 'Are you sure you want to permanently delete this quest?',
    warning: 'This action cannot be undone. The quest will be permanently removed.',
    cancel: 'Cancel',
    confirm: 'Delete Quest',
    deleting: 'Deleting...',
  },
  exitQuest: {
    title: 'Exit Quest',
    description: 'You are about to exit this quest and receive a refund of your initial contribution.',
    yourContribution: 'Your Contribution',
    crowdfunding: 'Crowdfunding',
    contributors: 'contributors',
    refundInfo: 'You will receive a refund of your initial contribution. Crowdfunding contributions will remain in the quest.',
    cancel: 'Cancel',
    confirm: 'Exit & Refund',
    exiting: 'Exiting...',
  },
  abandonQuest: {
    title: 'Abandon Quest',
    description: 'You are about to abandon this quest. This will have serious consequences:',
    forfeitAmount: 'Forfeit Deposit',
    depositRateReset: 'New Deposit Rate',
    warning: 'Your deposit will be forfeited and your deposit rate will reset to 50% for future quests.',
    typeConfirm: 'Type CONFIRM to proceed',
    typeConfirmHint: 'Type "CONFIRM" in capital letters to enable the abandon button',
    cancel: 'Cancel',
    confirm: 'Abandon Quest',
    abandoning: 'Abandoning...',
  },
  dailyCheckIn: {
    title: 'Daily Check-In',
    day: 'Day',
    description: 'Record your progress for today',
    firstDayNote: 'This is your Day 1 baseline. Future comparisons will reference this.',
    progress: 'Progress',
    target: 'Target',
    days: 'days',
    statusUpdate: 'Status Update',
    statusPlaceholder: 'How did today go? Any challenges or wins?',
    photo: 'Progress Photo',
    uploadPhoto: 'Click to upload photo',
    photoOptional: 'Optional but recommended',
    uploading: 'Uploading',
    submit: 'Submit Check-In',
    submitting: 'Submitting...',
    requireContent: 'Please add a status update or photo',
    submitSuccess: 'Check-in submitted successfully!',
    submitError: 'Failed to submit check-in',
    fileTooLarge: 'File size must be less than 5MB',
  },
  visualComparison: {
    title: 'Visual Progress Comparison',
    day: 'Day',
    totalCheckIns: 'Total Check-ins',
    timeline: 'Full Timeline',
    autoGenerated: 'Auto-generated baseline photo',
  },
  disputeResolution: {
    title: 'Dispute Resolution',
    subtitle: 'Community-powered justice system',
    noDisputes: 'No active disputes',
    questTitle: 'Quest',
    publisher: 'Publisher',
    warrior: 'Warrior',
    publisherArgument: 'Publisher Argument',
    warriorArgument: 'Warrior Argument',
    voteDistribution: 'Vote Distribution',
    publisherVotes: 'Publisher',
    adminVotes: 'Admin',
    communityVotes: 'Community',
    voteForPublisher: 'Vote for Publisher',
    voteForWarrior: 'Vote for Warrior',
    votingClosed: 'Voting Closed',
  },
  appealSubmission: {
    title: 'Submit Appeal',
    description: 'Explain why you believe the dispute should be resolved in your favor',
    yourArgument: 'Your Argument',
    argumentPlaceholder: 'Provide detailed evidence and reasoning...',
    minCharacters: 'Minimum 100 characters required',
    submit: 'Submit Appeal',
    submitting: 'Submitting...',
    argumentTooShort: 'Argument must be at least 100 characters',
    submitSuccess: 'Appeal submitted successfully!',
    submitError: 'Failed to submit appeal',
    viewAppeal: 'View Submitted Appeal',
    yourAppeal: 'Your Appeal',
    noAppeal: 'No appeal submitted yet',
  },
  footer: {
    builtWith: 'Built with',
    love: 'love',
    using: 'using',
  },
};

export const translations: Record<Language, TranslationStructure> = {
  [Language.English]: englishTranslations,
  [Language.SimplifiedChinese]: {
    splash: {
      question: '坚持会让你变得更强大,还是毫无意义?',
      subtext: '如果"当初"变为现实,你真的会更优秀吗?',
      enter: '进入',
    },
    language: {
      select: '选择您的语言',
      english: 'English',
      chinese: '简体中文',
      spanish: 'Español',
      french: 'Français',
      japanese: '日本語',
      korean: '한국어',
    },
    auth: {
      login: '登录',
      logout: '登出',
      loggingIn: '登录中...',
    },
    profile: {
      setupTitle: '欢迎,勇士',
      setupDescription: '输入您的名字开始旅程',
      namePlaceholder: '您的名字',
      save: '保存',
      saving: '保存中...',
    },
    nav: {
      bountyBoard: '悬赏大厅',
      launchMission: '发布任务',
      disputeResolution: '争议解决',
      personalCenter: '个人中心',
    },
    bountyBoard: {
      title: '悬赏大厅',
      allQuests: '全部任务',
      noQuests: '暂无任务',
      hype: '热度',
      contributors: '贡献者',
      acceptSuccess: '成功接受任务!',
      acceptError: '接受任务失败',
      yourQuest: '您的任务',
      addToPot: '加入奖池',
      addToPotDescription: '增加奖池以吸引更多勇士',
      currentPool: '当前奖池',
      yourContribution: '您的贡献',
      newPool: '新奖池',
      contribute: '贡献',
      contributionSuccess: '贡献成功!',
      contributionError: '贡献失败',
    },
    difficulty: {
      easy: '简单',
      medium: '中等',
      hard: '困难',
      extreme: '极难',
      impossible: '几乎不可能',
    },
    deposit: {
      required: '需要押金',
      acceptAndPayDeposit: '接受并支付押金',
      confirmTitle: '确认押金',
      confirmDescription: '锁定押金以接受此任务',
      questTitle: '任务',
      rewardPool: '奖池',
      yourDepositRate: '您的押金率',
      depositRequired: '需要押金',
      depositInfo: '您的押金将被锁定直到任务完成。成功完成可获得奖励并降低押金率。',
      cancel: '取消',
      confirmAndPay: '确认并支付',
      processing: '处理中...',
      transferFailed: '转账失败',
    },
    launchMission: {
      title: '发布任务',
      subtitle: '创建新任务并设定挑战',
      questTitle: '任务标题',
      titlePlaceholder: '例如:连续100天早上5点起床',
      rules: '任务规则与描述',
      rulesPlaceholder: '描述任务要求和规则...',
      rewardPool: '初始奖池 (ICP)',
      rewardHint: '最少 0.0001 ICP',
      difficulty: '难度等级',
      createQuest: '创建任务',
      creating: '创建中...',
      fillAllFields: '请填写所有字段',
      invalidReward: '请输入有效的奖励金额',
      createSuccess: '任务创建成功!',
      createError: '创建任务失败',
      titleRequired: '任务标题必填',
      descriptionTooShort: '描述至少需要20个字符',
      minCharacters: '最少字符数',
    },
    creditScore: {
      title: '勇士信用评分',
      depositRate: '当前押金率',
      successfulQuests: '成功任务',
      totalEarned: '总收入',
      totalDeposited: '总押金',
      questsToMinimum: '次任务达到最低率 (2%)',
      rateDecrease: '每次成功: -3%',
    },
    personalCenter: {
      title: '个人中心',
      subtitle: '追踪您的任务和进度',
      acceptedQuests: '已接受任务',
      postedBounties: '已发布悬赏',
      noAcceptedQuests: '暂无已接受任务',
      noPostedBounties: '暂无已发布悬赏',
      progress: '进度',
      status: '状态',
      reward: '奖励',
      lockedDeposit: '锁定押金',
      rewardPool: '奖池',
      hypeCount: '热度',
      warrior: '勇士',
      checkIn: '打卡',
      viewProgress: '查看进度',
      deleteQuest: '删除',
      exitQuest: '退出',
      abandonQuest: '放弃任务',
      statusActive: '活跃',
      statusInProgress: '进行中',
      statusPending: '待验证',
      statusCompleted: '已完成',
      statusDisputed: '争议中',
      statusCancelled: '已取消',
    },
    deleteQuest: {
      title: '删除任务',
      description: '您确定要永久删除此任务吗?',
      warning: '此操作无法撤销。任务将被永久删除。',
      cancel: '取消',
      confirm: '删除任务',
      deleting: '删除中...',
    },
    exitQuest: {
      title: '退出任务',
      description: '您即将退出此任务并获得初始贡献的退款。',
      yourContribution: '您的贡献',
      crowdfunding: '众筹',
      contributors: '贡献者',
      refundInfo: '您将获得初始贡献的退款。众筹贡献将保留在任务中。',
      cancel: '取消',
      confirm: '退出并退款',
      exiting: '退出中...',
    },
    abandonQuest: {
      title: '放弃任务',
      description: '您即将放弃此任务。这将产生严重后果:',
      forfeitAmount: '没收押金',
      depositRateReset: '新押金率',
      warning: '您的押金将被没收,押金率将重置为50%。',
      typeConfirm: '输入 CONFIRM 继续',
      typeConfirmHint: '输入大写字母"CONFIRM"以启用放弃按钮',
      cancel: '取消',
      confirm: '放弃任务',
      abandoning: '放弃中...',
    },
    dailyCheckIn: {
      title: '每日打卡',
      day: '第',
      description: '记录今天的进度',
      firstDayNote: '这是您的第1天基准。未来的对比将参考此记录。',
      progress: '进度',
      target: '目标',
      days: '天',
      statusUpdate: '状态更新',
      statusPlaceholder: '今天怎么样?有什么挑战或收获?',
      photo: '进度照片',
      uploadPhoto: '点击上传照片',
      photoOptional: '可选但推荐',
      uploading: '上传中',
      submit: '提交打卡',
      submitting: '提交中...',
      requireContent: '请添加状态更新或照片',
      submitSuccess: '打卡提交成功!',
      submitError: '打卡提交失败',
      fileTooLarge: '文件大小必须小于5MB',
    },
    visualComparison: {
      title: '视觉进度对比',
      day: '第',
      totalCheckIns: '总打卡次数',
      timeline: '完整时间线',
      autoGenerated: '自动生成的基准照片',
    },
    disputeResolution: {
      title: '争议解决',
      subtitle: '社区驱动的公正系统',
      noDisputes: '暂无活跃争议',
      questTitle: '任务',
      publisher: '发布者',
      warrior: '勇士',
      publisherArgument: '发布者论据',
      warriorArgument: '勇士论据',
      voteDistribution: '投票分布',
      publisherVotes: '发布者',
      adminVotes: '管理员',
      communityVotes: '社区',
      voteForPublisher: '支持发布者',
      voteForWarrior: '支持勇士',
      votingClosed: '投票已关闭',
    },
    appealSubmission: {
      title: '提交申诉',
      description: '解释为什么您认为争议应该以您的方式解决',
      yourArgument: '您的论据',
      argumentPlaceholder: '提供详细的证据和理由...',
      minCharacters: '至少需要100个字符',
      submit: '提交申诉',
      submitting: '提交中...',
      argumentTooShort: '论据至少需要100个字符',
      submitSuccess: '申诉提交成功!',
      submitError: '申诉提交失败',
      viewAppeal: '查看已提交的申诉',
      yourAppeal: '您的申诉',
      noAppeal: '尚未提交申诉',
    },
    footer: {
      builtWith: '构建于',
      love: '爱',
      using: '使用',
    },
  },
  [Language.TraditionalChinese]: {
    splash: {
      question: '堅持會讓你變得更強大,還是毫無意義?',
      subtext: '如果"當初"變為現實,你真的會更優秀嗎?',
      enter: '進入',
    },
    language: {
      select: '選擇您的語言',
      english: 'English',
      chinese: '繁體中文',
      spanish: 'Español',
      french: 'Français',
      japanese: '日本語',
      korean: '한국어',
    },
    auth: {
      login: '登入',
      logout: '登出',
      loggingIn: '登入中...',
    },
    profile: {
      setupTitle: '歡迎,勇士',
      setupDescription: '輸入您的名字開始旅程',
      namePlaceholder: '您的名字',
      save: '儲存',
      saving: '儲存中...',
    },
    nav: {
      bountyBoard: '懸賞大廳',
      launchMission: '發布任務',
      disputeResolution: '爭議解決',
      personalCenter: '個人中心',
    },
    bountyBoard: {
      title: '懸賞大廳',
      allQuests: '全部任務',
      noQuests: '暫無任務',
      hype: '熱度',
      contributors: '貢獻者',
      acceptSuccess: '成功接受任務!',
      acceptError: '接受任務失敗',
      yourQuest: '您的任務',
      addToPot: '加入獎池',
      addToPotDescription: '增加獎池以吸引更多勇士',
      currentPool: '當前獎池',
      yourContribution: '您的貢獻',
      newPool: '新獎池',
      contribute: '貢獻',
      contributionSuccess: '貢獻成功!',
      contributionError: '貢獻失敗',
    },
    difficulty: {
      easy: '簡單',
      medium: '中等',
      hard: '困難',
      extreme: '極難',
      impossible: '幾乎不可能',
    },
    deposit: {
      required: '需要押金',
      acceptAndPayDeposit: '接受並支付押金',
      confirmTitle: '確認押金',
      confirmDescription: '鎖定押金以接受此任務',
      questTitle: '任務',
      rewardPool: '獎池',
      yourDepositRate: '您的押金率',
      depositRequired: '需要押金',
      depositInfo: '您的押金將被鎖定直到任務完成。成功完成可獲得獎勵並降低押金率。',
      cancel: '取消',
      confirmAndPay: '確認並支付',
      processing: '處理中...',
      transferFailed: '轉帳失敗',
    },
    launchMission: {
      title: '發布任務',
      subtitle: '創建新任務並設定挑戰',
      questTitle: '任務標題',
      titlePlaceholder: '例如:連續100天早上5點起床',
      rules: '任務規則與描述',
      rulesPlaceholder: '描述任務要求和規則...',
      rewardPool: '初始獎池 (ICP)',
      rewardHint: '最少 0.0001 ICP',
      difficulty: '難度等級',
      createQuest: '創建任務',
      creating: '創建中...',
      fillAllFields: '請填寫所有欄位',
      invalidReward: '請輸入有效的獎勵金額',
      createSuccess: '任務創建成功!',
      createError: '創建任務失敗',
      titleRequired: '任務標題必填',
      descriptionTooShort: '描述至少需要20個字符',
      minCharacters: '最少字符數',
    },
    creditScore: {
      title: '勇士信用評分',
      depositRate: '當前押金率',
      successfulQuests: '成功任務',
      totalEarned: '總收入',
      totalDeposited: '總押金',
      questsToMinimum: '次任務達到最低率 (2%)',
      rateDecrease: '每次成功: -3%',
    },
    personalCenter: {
      title: '個人中心',
      subtitle: '追蹤您的任務和進度',
      acceptedQuests: '已接受任務',
      postedBounties: '已發布懸賞',
      noAcceptedQuests: '暫無已接受任務',
      noPostedBounties: '暫無已發布懸賞',
      progress: '進度',
      status: '狀態',
      reward: '獎勵',
      lockedDeposit: '鎖定押金',
      rewardPool: '獎池',
      hypeCount: '熱度',
      warrior: '勇士',
      checkIn: '打卡',
      viewProgress: '查看進度',
      deleteQuest: '刪除',
      exitQuest: '退出',
      abandonQuest: '放棄任務',
      statusActive: '活躍',
      statusInProgress: '進行中',
      statusPending: '待驗證',
      statusCompleted: '已完成',
      statusDisputed: '爭議中',
      statusCancelled: '已取消',
    },
    deleteQuest: {
      title: '刪除任務',
      description: '您確定要永久刪除此任務嗎?',
      warning: '此操作無法撤銷。任務將被永久刪除。',
      cancel: '取消',
      confirm: '刪除任務',
      deleting: '刪除中...',
    },
    exitQuest: {
      title: '退出任務',
      description: '您即將退出此任務並獲得初始貢獻的退款。',
      yourContribution: '您的貢獻',
      crowdfunding: '眾籌',
      contributors: '貢獻者',
      refundInfo: '您將獲得初始貢獻的退款。眾籌貢獻將保留在任務中。',
      cancel: '取消',
      confirm: '退出並退款',
      exiting: '退出中...',
    },
    abandonQuest: {
      title: '放棄任務',
      description: '您即將放棄此任務。這將產生嚴重後果:',
      forfeitAmount: '沒收押金',
      depositRateReset: '新押金率',
      warning: '您的押金將被沒收,押金率將重置為50%。',
      typeConfirm: '輸入 CONFIRM 繼續',
      typeConfirmHint: '輸入大寫字母"CONFIRM"以啟用放棄按鈕',
      cancel: '取消',
      confirm: '放棄任務',
      abandoning: '放棄中...',
    },
    dailyCheckIn: {
      title: '每日打卡',
      day: '第',
      description: '記錄今天的進度',
      firstDayNote: '這是您的第1天基準。未來的對比將參考此記錄。',
      progress: '進度',
      target: '目標',
      days: '天',
      statusUpdate: '狀態更新',
      statusPlaceholder: '今天怎麼樣?有什麼挑戰或收穫?',
      photo: '進度照片',
      uploadPhoto: '點擊上傳照片',
      photoOptional: '可選但推薦',
      uploading: '上傳中',
      submit: '提交打卡',
      submitting: '提交中...',
      requireContent: '請添加狀態更新或照片',
      submitSuccess: '打卡提交成功!',
      submitError: '打卡提交失敗',
      fileTooLarge: '檔案大小必須小於5MB',
    },
    visualComparison: {
      title: '視覺進度對比',
      day: '第',
      totalCheckIns: '總打卡次數',
      timeline: '完整時間線',
      autoGenerated: '自動生成的基準照片',
    },
    disputeResolution: {
      title: '爭議解決',
      subtitle: '社區驅動的公正系統',
      noDisputes: '暫無活躍爭議',
      questTitle: '任務',
      publisher: '發布者',
      warrior: '勇士',
      publisherArgument: '發布者論據',
      warriorArgument: '勇士論據',
      voteDistribution: '投票分佈',
      publisherVotes: '發布者',
      adminVotes: '管理員',
      communityVotes: '社區',
      voteForPublisher: '支持發布者',
      voteForWarrior: '支持勇士',
      votingClosed: '投票已關閉',
    },
    appealSubmission: {
      title: '提交申訴',
      description: '解釋為什麼您認為爭議應該以您的方式解決',
      yourArgument: '您的論據',
      argumentPlaceholder: '提供詳細的證據和理由...',
      minCharacters: '至少需要100個字符',
      submit: '提交申訴',
      submitting: '提交中...',
      argumentTooShort: '論據至少需要100個字符',
      submitSuccess: '申訴提交成功!',
      submitError: '申訴提交失敗',
      viewAppeal: '查看已提交的申訴',
      yourAppeal: '您的申訴',
      noAppeal: '尚未提交申訴',
    },
    footer: {
      builtWith: '構建於',
      love: '愛',
      using: '使用',
    },
  },
};
