import { Language } from '../types';

type TranslationStructure = {
  splash: {
    question: string;
    subtext: string;
    enter: string;
    subtitle: string;
    tagline: string;
    feature1Title: string;
    feature1Desc: string;
    feature2Title: string;
    feature2Desc: string;
    feature3Title: string;
    feature3Desc: string;
  };
  language: {
    select: string;
    english: string;
    chinese: string;
    spanish: string;
    french: string;
    japanese: string;
    korean: string;
  };
  auth: {
    login: string;
    logout: string;
    loggingIn: string;
  };
  profile: {
    setupTitle: string;
    setupDescription: string;
    namePlaceholder: string;
    save: string;
    saving: string;
  };
  nav: {
    bountyBoard: string;
    launchMission: string;
    disputeResolution: string;
    personalCenter: string;
  };
  bountyBoard: {
    title: string;
    allQuests: string;
    noQuests: string;
    hype: string;
    contributors: string;
    acceptSuccess: string;
    acceptError: string;
    yourQuest: string;
    addToPot: string;
    addToPotDescription: string;
    currentPool: string;
    yourContribution: string;
    newPool: string;
    contribute: string;
    contributionSuccess: string;
    contributionError: string;
  };
  difficulty: {
    easy: string;
    medium: string;
    hard: string;
    extreme: string;
    impossible: string;
  };
  deposit: {
    required: string;
    acceptAndPayDeposit: string;
    confirmTitle: string;
    confirmDescription: string;
    questTitle: string;
    rewardPool: string;
    yourDepositRate: string;
    depositRequired: string;
    depositInfo: string;
    cancel: string;
    confirmAndPay: string;
    processing: string;
    transferFailed: string;
  };
  launchMission: {
    title: string;
    subtitle: string;
    questTitle: string;
    titlePlaceholder: string;
    rules: string;
    rulesPlaceholder: string;
    rewardPool: string;
    rewardHint: string;
    difficulty: string;
    createQuest: string;
    creating: string;
    fillAllFields: string;
    invalidReward: string;
    createSuccess: string;
    createError: string;
    titleRequired: string;
    descriptionTooShort: string;
    minCharacters: string;
  };
  creditScore: {
    title: string;
    depositRate: string;
    successfulQuests: string;
    totalEarned: string;
    totalDeposited: string;
    questsToMinimum: string;
    rateDecrease: string;
  };
  personalCenter: {
    title: string;
    subtitle: string;
    acceptedQuests: string;
    postedBounties: string;
    noAcceptedQuests: string;
    noPostedBounties: string;
    progress: string;
    status: string;
    reward: string;
    lockedDeposit: string;
    rewardPool: string;
    hypeCount: string;
    warrior: string;
    checkIn: string;
    viewProgress: string;
    deleteQuest: string;
    exitQuest: string;
    abandonQuest: string;
    statusActive: string;
    statusInProgress: string;
    statusPending: string;
    statusCompleted: string;
    statusDisputed: string;
    statusCancelled: string;
  };
  deleteQuest: {
    title: string;
    description: string;
    warning: string;
    cancel: string;
    confirm: string;
    deleting: string;
  };
  exitQuest: {
    title: string;
    description: string;
    yourContribution: string;
    crowdfunding: string;
    contributors: string;
    refundInfo: string;
    cancel: string;
    confirm: string;
    exiting: string;
  };
  abandonQuest: {
    title: string;
    description: string;
    forfeitAmount: string;
    depositRateReset: string;
    warning: string;
    typeConfirm: string;
    typeConfirmHint: string;
    cancel: string;
    confirm: string;
    abandoning: string;
  };
  dailyCheckIn: {
    title: string;
    day: string;
    description: string;
    firstDayNote: string;
    progress: string;
    target: string;
    days: string;
    statusUpdate: string;
    statusPlaceholder: string;
    photo: string;
    uploadPhoto: string;
    photoOptional: string;
    uploading: string;
    submit: string;
    submitting: string;
    requireContent: string;
    submitSuccess: string;
    submitError: string;
    fileTooLarge: string;
  };
  visualComparison: {
    title: string;
    day: string;
    totalCheckIns: string;
    timeline: string;
    autoGenerated: string;
  };
  disputeResolution: {
    title: string;
    subtitle: string;
    noDisputes: string;
    questTitle: string;
    publisher: string;
    warrior: string;
    publisherArgument: string;
    warriorArgument: string;
    voteDistribution: string;
    publisherVotes: string;
    adminVotes: string;
    communityVotes: string;
    voteForPublisher: string;
    voteForWarrior: string;
    votingClosed: string;
  };
  appealSubmission: {
    title: string;
    description: string;
    yourArgument: string;
    argumentPlaceholder: string;
    minCharacters: string;
    submit: string;
    submitting: string;
    argumentTooShort: string;
    submitSuccess: string;
    submitError: string;
    viewAppeal: string;
    yourAppeal: string;
    noAppeal: string;
  };
  introduction: {
    linkText: string;
    title: string;
    subtitle: string;
    coreMission: {
      title: string;
      content: string;
    };
    useCases: {
      title: string;
      intro: string;
      lifestyle: string;
      lifestyleExample: string;
      health: string;
      healthExample: string;
      exercise: string;
      exerciseExample: string;
      social: string;
      socialExample: string;
      enterprise: string;
      enterpriseExample: string;
      more: string;
      moreExample: string;
    };
    bountyMechanism: {
      title: string;
      publishTitle: string;
      publishContent: string;
      crowdfundTitle: string;
      crowdfundContent: string;
      acceptTitle: string;
      acceptContent: string;
      flexibleTitle: string;
      flexibleContent: string;
    };
    settlementRules: {
      title: string;
      successTitle: string;
      successContent: string;
      unclaimedTitle: string;
      unclaimedContent: string;
      defaultTitle: string;
      defaultContent: string;
      feesTitle: string;
      feesSuccessLabel: string;
      feesSuccessContent: string;
      feesDefaultLabel: string;
      feesDefaultContent: string;
    };
    warriorCredit: {
      title: string;
      intro: string;
      initialTitle: string;
      initialContent: string;
      rewardTitle: string;
      rewardContent: string;
      capTitle: string;
      capContent: string;
      penaltyTitle: string;
      penaltyContent: string;
    };
  };
  footer: {
    builtWith: string;
    love: string;
    using: string;
  };
};

// Base English translations
const englishTranslations: TranslationStructure = {
  splash: {
    question: 'Will persistence make you stronger, or is it meaningless?',
    subtext: 'If "what if" became reality, would you truly be better?',
    enter: 'ENTER',
    subtitle: 'Turn "What If" Into Reality',
    tagline: 'Challenge yourself. Prove your grit. Earn rewards.',
    feature1Title: 'Set Challenges',
    feature1Desc: 'Create quests that test persistence and commitment',
    feature2Title: 'Earn Rewards',
    feature2Desc: 'Complete challenges and earn ICP tokens',
    feature3Title: 'Build Trust',
    feature3Desc: 'Lower your deposit rate with each successful quest',
  },
  language: {
    select: 'Select Your Language',
    english: 'English',
    chinese: 'Chinese',
    spanish: 'Spanish',
    french: 'French',
    japanese: 'Japanese',
    korean: 'Korean',
  },
  auth: {
    login: 'Login',
    logout: 'Logout',
    loggingIn: 'Logging in...',
  },
  profile: {
    setupTitle: 'Welcome, Warrior',
    setupDescription: 'Enter your name to begin your journey',
    namePlaceholder: 'Your name',
    save: 'Save',
    saving: 'Saving...',
  },
  nav: {
    bountyBoard: 'Bounty Board',
    launchMission: 'Launch Mission',
    disputeResolution: 'Dispute Resolution',
    personalCenter: 'Personal Center',
  },
  bountyBoard: {
    title: 'Bounty Board',
    allQuests: 'All Quests',
    noQuests: 'No quests available',
    hype: 'Hype',
    contributors: 'contributors',
    acceptSuccess: 'Quest accepted successfully!',
    acceptError: 'Failed to accept quest',
    yourQuest: 'Your Quest',
    addToPot: 'Add to Pot',
    addToPotDescription: 'Increase the reward pool to attract more warriors',
    currentPool: 'Current Pool',
    yourContribution: 'Your Contribution',
    newPool: 'New Pool',
    contribute: 'Contribute',
    contributionSuccess: 'Contribution added successfully!',
    contributionError: 'Failed to add contribution',
  },
  difficulty: {
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    extreme: 'Extreme',
    impossible: 'Impossible',
  },
  deposit: {
    required: 'Deposit Required',
    acceptAndPayDeposit: 'Accept & Pay Deposit',
    confirmTitle: 'Confirm Deposit',
    confirmDescription: 'Lock your deposit to accept this quest',
    questTitle: 'Quest',
    rewardPool: 'Reward Pool',
    yourDepositRate: 'Your Deposit Rate',
    depositRequired: 'Deposit Required',
    depositInfo: 'Your deposit will be locked until quest completion. Complete successfully to earn rewards and reduce your deposit rate.',
    cancel: 'Cancel',
    confirmAndPay: 'Confirm & Pay',
    processing: 'Processing...',
    transferFailed: 'Transfer failed',
  },
  launchMission: {
    title: 'Launch Mission',
    subtitle: 'Create a new quest and set the challenge',
    questTitle: 'Quest Title',
    titlePlaceholder: 'e.g., Wake up at 5 AM for 100 days',
    rules: 'Quest Rules & Description',
    rulesPlaceholder: 'Describe the quest requirements and rules...',
    rewardPool: 'Initial Reward Pool (ICP)',
    rewardHint: 'Minimum 0.0001 ICP',
    difficulty: 'Difficulty Level',
    createQuest: 'Create Quest',
    creating: 'Creating...',
    fillAllFields: 'Please fill in all fields',
    invalidReward: 'Please enter a valid reward amount',
    createSuccess: 'Quest created successfully!',
    createError: 'Failed to create quest',
    titleRequired: 'Quest title is required',
    descriptionTooShort: 'Description must be at least 20 characters',
    minCharacters: 'characters minimum',
  },
  creditScore: {
    title: 'Warrior Credit Score',
    depositRate: 'Current Deposit Rate',
    successfulQuests: 'Successful Quests',
    totalEarned: 'Total Earned',
    totalDeposited: 'Total Deposited',
    questsToMinimum: 'quests to minimum rate (2%)',
    rateDecrease: 'Each success: -3%',
  },
  personalCenter: {
    title: 'Personal Center',
    subtitle: 'Track your quests and progress',
    acceptedQuests: 'Accepted Quests',
    postedBounties: 'Posted Bounties',
    noAcceptedQuests: 'No accepted quests yet',
    noPostedBounties: 'No posted bounties yet',
    progress: 'Progress',
    status: 'Status',
    reward: 'Reward',
    lockedDeposit: 'Locked Deposit',
    rewardPool: 'Reward Pool',
    hypeCount: 'Hype Count',
    warrior: 'Warrior',
    checkIn: 'Check In',
    viewProgress: 'View Progress',
    deleteQuest: 'Delete',
    exitQuest: 'Exit',
    abandonQuest: 'Abandon Quest',
    statusActive: 'Active',
    statusInProgress: 'In Progress',
    statusPending: 'Pending',
    statusCompleted: 'Completed',
    statusDisputed: 'Disputed',
    statusCancelled: 'Cancelled',
  },
  deleteQuest: {
    title: 'Delete Quest',
    description: 'Are you sure you want to permanently delete this quest?',
    warning: 'This action cannot be undone. The quest will be permanently removed.',
    cancel: 'Cancel',
    confirm: 'Delete Quest',
    deleting: 'Deleting...',
  },
  exitQuest: {
    title: 'Exit Quest',
    description: 'You are about to exit this quest and receive a refund of your initial contribution.',
    yourContribution: 'Your Contribution',
    crowdfunding: 'Crowdfunding',
    contributors: 'contributors',
    refundInfo: 'You will receive a refund of your initial contribution. Crowdfunding contributions will remain in the quest.',
    cancel: 'Cancel',
    confirm: 'Exit & Refund',
    exiting: 'Exiting...',
  },
  abandonQuest: {
    title: 'Abandon Quest',
    description: 'You are about to abandon this quest. This will have serious consequences:',
    forfeitAmount: 'Forfeit Deposit',
    depositRateReset: 'New Deposit Rate',
    warning: 'Your deposit will be forfeited and your deposit rate will reset to 50% for future quests.',
    typeConfirm: 'Type CONFIRM to proceed',
    typeConfirmHint: 'Type "CONFIRM" in capital letters to enable the abandon button',
    cancel: 'Cancel',
    confirm: 'Abandon Quest',
    abandoning: 'Abandoning...',
  },
  dailyCheckIn: {
    title: 'Daily Check-In',
    day: 'Day',
    description: 'Record your progress for today',
    firstDayNote: 'This is your Day 1 baseline. Future comparisons will reference this.',
    progress: 'Progress',
    target: 'Target',
    days: 'days',
    statusUpdate: 'Status Update',
    statusPlaceholder: 'How did today go? Any challenges or wins?',
    photo: 'Progress Photo',
    uploadPhoto: 'Click to upload photo',
    photoOptional: 'Optional but recommended',
    uploading: 'Uploading',
    submit: 'Submit Check-In',
    submitting: 'Submitting...',
    requireContent: 'Please add a status update or photo',
    submitSuccess: 'Check-in submitted successfully!',
    submitError: 'Failed to submit check-in',
    fileTooLarge: 'File size must be less than 5MB',
  },
  visualComparison: {
    title: 'Visual Progress Comparison',
    day: 'Day',
    totalCheckIns: 'Total Check-ins',
    timeline: 'Full Timeline',
    autoGenerated: 'Auto-generated baseline photo',
  },
  disputeResolution: {
    title: 'Dispute Resolution',
    subtitle: 'Community-powered justice system',
    noDisputes: 'No active disputes',
    questTitle: 'Quest',
    publisher: 'Publisher',
    warrior: 'Warrior',
    publisherArgument: 'Publisher Argument',
    warriorArgument: 'Warrior Argument',
    voteDistribution: 'Vote Distribution',
    publisherVotes: 'Publisher',
    adminVotes: 'Admin',
    communityVotes: 'Community',
    voteForPublisher: 'Vote for Publisher',
    voteForWarrior: 'Vote for Warrior',
    votingClosed: 'Voting Closed',
  },
  appealSubmission: {
    title: 'Submit Appeal',
    description: 'Explain why you believe the dispute should be resolved in your favor',
    yourArgument: 'Your Argument',
    argumentPlaceholder: 'Provide detailed evidence and reasoning...',
    minCharacters: 'Minimum 100 characters required',
    submit: 'Submit Appeal',
    submitting: 'Submitting...',
    argumentTooShort: 'Argument must be at least 100 characters',
    submitSuccess: 'Appeal submitted successfully!',
    submitError: 'Failed to submit appeal',
    viewAppeal: 'View Submitted Appeal',
    yourAppeal: 'Your Appeal',
    noAppeal: 'No appeal submitted yet',
  },
  introduction: {
    linkText: 'How it works? (运作规则)',
    title: 'Grit Bounty',
    subtitle: 'Turn "What If" Into Reality',
    coreMission: {
      title: 'Our Core Mission',
      content:
        'If you once had a goal to persist but didn\'t follow through, yet still wonder what would have happened if you had—now is the time! We make it real!',
    },
    useCases: {
      title: 'No Matter How Unique Your Idea',
      intro:
        'Most people have their own ideas and creativity, but often fail to persist for various reasons. Now, our warriors help you realize them:',
      lifestyle: 'Lifestyle Routine',
      lifestyleExample: 'Wake up at 5 AM every day.',
      health: 'Healthy Diet',
      healthExample: 'Eat only vegetables for a month, or consume 1-2 grams of vitamin C daily.',
      exercise: 'Exercise Challenge',
      exerciseExample: 'Run 10 kilometers daily, or hike to specific locations.',
      social: 'Social Creativity',
      socialExample: 'Make 3 new friends of the opposite gender daily.',
      enterprise: 'Enterprise Use',
      enterpriseExample: 'Promote new apps, collect user feedback, and incentivize participation.',
      more: 'More Possibilities',
      moreExample: 'And any other unusual challenges.',
    },
    bountyMechanism: {
      title: 'Bounty & Operation Mechanism',
      publishTitle: 'Publish Task',
      publishContent:
        'Simply publish your task and stake your credit currency (e.g., 100 ICP). Fill in the number of executors, total bounty for task completion, and pay the bounty to the platform immediately.',
      crowdfundTitle: 'Crowdfunding',
      crowdfundContent:
        'Attract like-minded people who also want to see the results. They can enter and contribute tips. When the bounty accumulates to a level where warriors are willing to accept, they can choose to take on the task.',
      acceptTitle: 'Warrior Acceptance',
      acceptContent:
        'Warriors who believe they can persist and accomplish this meaningful task can accept it and submit a portion of ICP as collateral.',
      flexibleTitle: 'Flexible Settings',
      flexibleContent:
        'Publishers can freely increase the number of warriors—one, two, or more.',
    },
    settlementRules: {
      title: 'Settlement & Fee Structure',
      successTitle: 'Task Success',
      successContent:
        'Upon successful completion by the deadline, the task automatically unlocks, the bounty is sent to the warrior\'s wallet, and the deposit is automatically returned to the warrior\'s account.',
      unclaimedTitle: 'Task Unclaimed',
      unclaimedContent:
        'If the task is not accepted, both the bounty and deposit are fully refunded to the publisher.',
      defaultTitle: 'Default Penalty',
      defaultContent:
        'If the task is accepted but the warrior fails to complete it, all of the warrior\'s deposit is forfeited, and the bounty is returned to the publisher.',
      feesTitle: 'Platform Fees',
      feesSuccessLabel: 'Task Success',
      feesSuccessContent: 'The platform takes 6% as operational fees.',
      feesDefaultLabel: 'Task Default (Warrior Incomplete)',
      feesDefaultContent:
        'The platform takes 6% of the warrior\'s deposit, and the remaining 94% goes to the publisher.',
    },
    warriorCredit: {
      title: 'Warrior Credit Reduction System',
      intro: 'We encourage true warriors through a tiered deposit system:',
      initialTitle: 'Initial Threshold',
      initialContent: 'Start with a 50% deposit.',
      rewardTitle: 'Success Reward',
      rewardContent:
        'Each successful task completion reduces the next deposit requirement by 3%.',
      capTitle: 'Integrity Cap',
      capContent:
        'Continue the cycle until the deposit drops to 2% (achieved after 16 successful tasks).',
      penaltyTitle: 'Penalty Mechanism',
      penaltyContent:
        'If you abandon a task midway or fail a dispute vote, your deposit immediately resets to 50% and the cycle restarts.',
    },
  },
  footer: {
    builtWith: 'Built with',
    love: 'love',
    using: 'using',
  },
};

export const translations: Record<Language, TranslationStructure> = {
  [Language.English]: englishTranslations,
  [Language.SimplifiedChinese]: {
    splash: {
      question: '坚持会让你变得更强大,还是毫无意义?',
      subtext: '如果"当初"变为现实,你真的会更优秀吗?',
      enter: '进入',
      subtitle: '将"如果当初"变为现实',
      tagline: '挑战自我。证明毅力。赢取奖励。',
      feature1Title: '设定挑战',
      feature1Desc: '创建测试毅力和承诺的任务',
      feature2Title: '赢取奖励',
      feature2Desc: '完成挑战并赚取ICP代币',
      feature3Title: '建立信任',
      feature3Desc: '每次成功任务降低押金率',
    },
    language: {
      select: '选择您的语言',
      english: 'English',
      chinese: '简体中文',
      spanish: 'Español',
      french: 'Français',
      japanese: '日本語',
      korean: '한국어',
    },
    auth: {
      login: '登录',
      logout: '登出',
      loggingIn: '登录中...',
    },
    profile: {
      setupTitle: '欢迎,勇士',
      setupDescription: '输入您的名字开始旅程',
      namePlaceholder: '您的名字',
      save: '保存',
      saving: '保存中...',
    },
    nav: {
      bountyBoard: '悬赏大厅',
      launchMission: '发布任务',
      disputeResolution: '争议解决',
      personalCenter: '个人中心',
    },
    bountyBoard: {
      title: '悬赏大厅',
      allQuests: '全部任务',
      noQuests: '暂无任务',
      hype: '热度',
      contributors: '贡献者',
      acceptSuccess: '成功接受任务!',
      acceptError: '接受任务失败',
      yourQuest: '您的任务',
      addToPot: '加入奖池',
      addToPotDescription: '增加奖池以吸引更多勇士',
      currentPool: '当前奖池',
      yourContribution: '您的贡献',
      newPool: '新奖池',
      contribute: '贡献',
      contributionSuccess: '贡献成功!',
      contributionError: '贡献失败',
    },
    difficulty: {
      easy: '简单',
      medium: '中等',
      hard: '困难',
      extreme: '极难',
      impossible: '几乎不可能',
    },
    deposit: {
      required: '需要押金',
      acceptAndPayDeposit: '接受并支付押金',
      confirmTitle: '确认押金',
      confirmDescription: '锁定押金以接受此任务',
      questTitle: '任务',
      rewardPool: '奖池',
      yourDepositRate: '您的押金率',
      depositRequired: '需要押金',
      depositInfo: '您的押金将被锁定直到任务完成。成功完成可获得奖励并降低押金率。',
      cancel: '取消',
      confirmAndPay: '确认并支付',
      processing: '处理中...',
      transferFailed: '转账失败',
    },
    launchMission: {
      title: '发布任务',
      subtitle: '创建新任务并设定挑战',
      questTitle: '任务标题',
      titlePlaceholder: '例如:连续100天早上5点起床',
      rules: '任务规则与描述',
      rulesPlaceholder: '描述任务要求和规则...',
      rewardPool: '初始奖池 (ICP)',
      rewardHint: '最少 0.0001 ICP',
      difficulty: '难度等级',
      createQuest: '创建任务',
      creating: '创建中...',
      fillAllFields: '请填写所有字段',
      invalidReward: '请输入有效的奖励金额',
      createSuccess: '任务创建成功!',
      createError: '创建任务失败',
      titleRequired: '任务标题必填',
      descriptionTooShort: '描述至少需要20个字符',
      minCharacters: '最少字符数',
    },
    creditScore: {
      title: '勇士信用评分',
      depositRate: '当前押金率',
      successfulQuests: '成功任务',
      totalEarned: '总收入',
      totalDeposited: '总押金',
      questsToMinimum: '次任务达到最低率 (2%)',
      rateDecrease: '每次成功: -3%',
    },
    personalCenter: {
      title: '个人中心',
      subtitle: '追踪您的任务和进度',
      acceptedQuests: '已接受任务',
      postedBounties: '已发布悬赏',
      noAcceptedQuests: '暂无已接受任务',
      noPostedBounties: '暂无已发布悬赏',
      progress: '进度',
      status: '状态',
      reward: '奖励',
      lockedDeposit: '锁定押金',
      rewardPool: '奖池',
      hypeCount: '热度',
      warrior: '勇士',
      checkIn: '打卡',
      viewProgress: '查看进度',
      deleteQuest: '删除',
      exitQuest: '退出',
      abandonQuest: '放弃任务',
      statusActive: '活跃',
      statusInProgress: '进行中',
      statusPending: '待验证',
      statusCompleted: '已完成',
      statusDisputed: '争议中',
      statusCancelled: '已取消',
    },
    deleteQuest: {
      title: '删除任务',
      description: '您确定要永久删除此任务吗?',
      warning: '此操作无法撤销。任务将被永久删除。',
      cancel: '取消',
      confirm: '删除任务',
      deleting: '删除中...',
    },
    exitQuest: {
      title: '退出任务',
      description: '您即将退出此任务并获得初始贡献的退款。',
      yourContribution: '您的贡献',
      crowdfunding: '众筹',
      contributors: '贡献者',
      refundInfo: '您将获得初始贡献的退款。众筹贡献将保留在任务中。',
      cancel: '取消',
      confirm: '退出并退款',
      exiting: '退出中...',
    },
    abandonQuest: {
      title: '放弃任务',
      description: '您即将放弃此任务。这将产生严重后果:',
      forfeitAmount: '没收押金',
      depositRateReset: '新押金率',
      warning: '您的押金将被没收,押金率将重置为50%。',
      typeConfirm: '输入 CONFIRM 继续',
      typeConfirmHint: '输入大写字母"CONFIRM"以启用放弃按钮',
      cancel: '取消',
      confirm: '放弃任务',
      abandoning: '放弃中...',
    },
    dailyCheckIn: {
      title: '每日打卡',
      day: '第',
      description: '记录今天的进度',
      firstDayNote: '这是您的第1天基准。未来的对比将参考此记录。',
      progress: '进度',
      target: '目标',
      days: '天',
      statusUpdate: '状态更新',
      statusPlaceholder: '今天怎么样?有什么挑战或收获?',
      photo: '进度照片',
      uploadPhoto: '点击上传照片',
      photoOptional: '可选但推荐',
      uploading: '上传中',
      submit: '提交打卡',
      submitting: '提交中...',
      requireContent: '请添加状态更新或照片',
      submitSuccess: '打卡提交成功!',
      submitError: '打卡提交失败',
      fileTooLarge: '文件大小必须小于5MB',
    },
    visualComparison: {
      title: '视觉进度对比',
      day: '第',
      totalCheckIns: '总打卡次数',
      timeline: '完整时间线',
      autoGenerated: '自动生成的基准照片',
    },
    disputeResolution: {
      title: '争议解决',
      subtitle: '社区驱动的公正系统',
      noDisputes: '暂无活跃争议',
      questTitle: '任务',
      publisher: '发布者',
      warrior: '勇士',
      publisherArgument: '发布者论据',
      warriorArgument: '勇士论据',
      voteDistribution: '投票分布',
      publisherVotes: '发布者',
      adminVotes: '管理员',
      communityVotes: '社区',
      voteForPublisher: '支持发布者',
      voteForWarrior: '支持勇士',
      votingClosed: '投票已关闭',
    },
    appealSubmission: {
      title: '提交申诉',
      description: '解释为什么您认为争议应该以您的方式解决',
      yourArgument: '您的论据',
      argumentPlaceholder: '提供详细的证据和理由...',
      minCharacters: '至少需要100个字符',
      submit: '提交申诉',
      submitting: '提交中...',
      argumentTooShort: '论据至少需要100个字符',
      submitSuccess: '申诉提交成功!',
      submitError: '申诉提交失败',
      viewAppeal: '查看已提交的申诉',
      yourAppeal: '您的申诉',
      noAppeal: '尚未提交申诉',
    },
    introduction: {
      linkText: 'How it works? (运作规则)',
      title: 'Grit Bounty',
      subtitle: '将"如果当初"变为现实',
      coreMission: {
        title: '一、我们的核心使命',
        content:
          '如果你曾经有一个坚持的目标,但是没有坚持下来,却又想知道如果当时坚持下去会发生什么样的结果——就是现在,我们把它变成现实!',
      },
      useCases: {
        title: '二、无论你的想法多么奇特',
        intro:
          '大多数人都有自己的想法跟创意,但往往因为各种原因没能长时间坚持。现在,我们的勇士帮你实现:',
        lifestyle: '生活作息',
        lifestyleExample: '坚持每天5点起床。',
        health: '健康饮食',
        healthExample: '坚持一个月每天只吃蔬菜,或每天坚持吃1-2克维生素C。',
        exercise: '运动挑战',
        exerciseExample: '每天跑步10公里,或徒步到某些地方。',
        social: '社交创意',
        socialExample: '每天坚持结交3个异性朋友。',
        enterprise: '企业推广',
        enterpriseExample: '企业可以推广新APP,收集用户反馈,激励用户参与。',
        more: '更多可能',
        moreExample: '以及任何其他奇怪的事情。',
      },
      bountyMechanism: {
        title: '三、悬赏与运作机制',
        publishTitle: '发布任务',
        publishContent:
          '你只需要发布任务,并押注自己的信用货币(如100 ICP)。发布时需填写执行人数、完成任务的总赏金,并立即向平台支付赏金。',
        crowdfundTitle: '众人加码',
        crowdfundContent:
          '吸引同样想看到结果的同类人群,他们可以进入并进行打赏。当赏金积累到大家愿意接任务的水平时,勇士可根据情况选择接取。',
        acceptTitle: '勇士领命',
        acceptContent:
          '认为自己能坚持并做到这件有意义事情的勇士,可以领取任务并提交部分ICP作为抵押。',
        flexibleTitle: '自由设定',
        flexibleContent: '悬赏者可以自由增加勇士数量,可以是一个、两个或更多。',
      },
      settlementRules: {
        title: '四、结算与费用说明',
        successTitle: '任务成功',
        successContent:
          '到期顺利坚持下来,任务自动解锁,赏金发放至勇士钱包,押金自动退回勇士账户。',
        unclaimedTitle: '任务未完成',
        unclaimedContent: '若任务未被领取,赏金与押金全部退回发布者。',
        defaultTitle: '违约赔付',
        defaultContent:
          '若任务被领取但勇士未完成,扣除勇士所有押金,赏金退回发布者。',
        feesTitle: '平台费用',
        feesSuccessLabel: '任务成功',
        feesSuccessContent: '平台抽取6%作为运营费用。',
        feesDefaultLabel: '任务违约(勇士未完成)',
        feesDefaultContent: '平台抽取勇士押金的6%,剩余94%的押金全部给发布者。',
      },
      warriorCredit: {
        title: '五、勇士信用减免系统',
        intro: '我们通过阶梯式押金制度鼓励真正的勇士:',
        initialTitle: '初始门槛',
        initialContent: '从50%押金开始起步。',
        rewardTitle: '成功奖励',
        rewardContent: '每成功完成一次任务,下次接单的押金比例减少3%。',
        capTitle: '诚信封顶',
        capContent:
          '持续循环直到押金降至2%(即成功完成16次任务后达到最低2%押金)。',
        penaltyTitle: '惩罚机制',
        penaltyContent:
          '如果中途放弃任务或争议投票失败,押金立即重置为50%并重新开始循环。',
      },
    },
    footer: {
      builtWith: '用',
      love: '爱',
      using: '构建,使用',
    },
  },
  [Language.TraditionalChinese]: {
    splash: {
      question: '堅持會讓你變得更強大,還是毫無意義?',
      subtext: '如果"當初"變為現實,你真的會更優秀嗎?',
      enter: '進入',
      subtitle: '將"如果當初"變為現實',
      tagline: '挑戰自我。證明毅力。贏取獎勵。',
      feature1Title: '設定挑戰',
      feature1Desc: '創建測試毅力和承諾的任務',
      feature2Title: '贏取獎勵',
      feature2Desc: '完成挑戰並賺取ICP代幣',
      feature3Title: '建立信任',
      feature3Desc: '每次成功任務降低押金率',
    },
    language: {
      select: '選擇您的語言',
      english: 'English',
      chinese: '繁體中文',
      spanish: 'Español',
      french: 'Français',
      japanese: '日本語',
      korean: '한국어',
    },
    auth: {
      login: '登入',
      logout: '登出',
      loggingIn: '登入中...',
    },
    profile: {
      setupTitle: '歡迎,勇士',
      setupDescription: '輸入您的名字開始旅程',
      namePlaceholder: '您的名字',
      save: '保存',
      saving: '保存中...',
    },
    nav: {
      bountyBoard: '懸賞大廳',
      launchMission: '發布任務',
      disputeResolution: '爭議解決',
      personalCenter: '個人中心',
    },
    bountyBoard: {
      title: '懸賞大廳',
      allQuests: '全部任務',
      noQuests: '暫無任務',
      hype: '熱度',
      contributors: '貢獻者',
      acceptSuccess: '成功接受任務!',
      acceptError: '接受任務失敗',
      yourQuest: '您的任務',
      addToPot: '加入獎池',
      addToPotDescription: '增加獎池以吸引更多勇士',
      currentPool: '當前獎池',
      yourContribution: '您的貢獻',
      newPool: '新獎池',
      contribute: '貢獻',
      contributionSuccess: '貢獻成功!',
      contributionError: '貢獻失敗',
    },
    difficulty: {
      easy: '簡單',
      medium: '中等',
      hard: '困難',
      extreme: '極難',
      impossible: '幾乎不可能',
    },
    deposit: {
      required: '需要押金',
      acceptAndPayDeposit: '接受並支付押金',
      confirmTitle: '確認押金',
      confirmDescription: '鎖定押金以接受此任務',
      questTitle: '任務',
      rewardPool: '獎池',
      yourDepositRate: '您的押金率',
      depositRequired: '需要押金',
      depositInfo: '您的押金將被鎖定直到任務完成。成功完成可獲得獎勵並降低押金率。',
      cancel: '取消',
      confirmAndPay: '確認並支付',
      processing: '處理中...',
      transferFailed: '轉賬失敗',
    },
    launchMission: {
      title: '發布任務',
      subtitle: '創建新任務並設定挑戰',
      questTitle: '任務標題',
      titlePlaceholder: '例如:連續100天早上5點起床',
      rules: '任務規則與描述',
      rulesPlaceholder: '描述任務要求和規則...',
      rewardPool: '初始獎池 (ICP)',
      rewardHint: '最少 0.0001 ICP',
      difficulty: '難度等級',
      createQuest: '創建任務',
      creating: '創建中...',
      fillAllFields: '請填寫所有字段',
      invalidReward: '請輸入有效的獎勵金額',
      createSuccess: '任務創建成功!',
      createError: '創建任務失敗',
      titleRequired: '任務標題必填',
      descriptionTooShort: '描述至少需要20個字符',
      minCharacters: '最少字符數',
    },
    creditScore: {
      title: '勇士信用評分',
      depositRate: '當前押金率',
      successfulQuests: '成功任務',
      totalEarned: '總收入',
      totalDeposited: '總押金',
      questsToMinimum: '次任務達到最低率 (2%)',
      rateDecrease: '每次成功: -3%',
    },
    personalCenter: {
      title: '個人中心',
      subtitle: '追蹤您的任務和進度',
      acceptedQuests: '已接受任務',
      postedBounties: '已發布懸賞',
      noAcceptedQuests: '暫無已接受任務',
      noPostedBounties: '暫無已發布懸賞',
      progress: '進度',
      status: '狀態',
      reward: '獎勵',
      lockedDeposit: '鎖定押金',
      rewardPool: '獎池',
      hypeCount: '熱度',
      warrior: '勇士',
      checkIn: '打卡',
      viewProgress: '查看進度',
      deleteQuest: '刪除',
      exitQuest: '退出',
      abandonQuest: '放棄任務',
      statusActive: '活躍',
      statusInProgress: '進行中',
      statusPending: '待驗證',
      statusCompleted: '已完成',
      statusDisputed: '爭議中',
      statusCancelled: '已取消',
    },
    deleteQuest: {
      title: '刪除任務',
      description: '您確定要永久刪除此任務嗎?',
      warning: '此操作無法撤銷。任務將被永久刪除。',
      cancel: '取消',
      confirm: '刪除任務',
      deleting: '刪除中...',
    },
    exitQuest: {
      title: '退出任務',
      description: '您即將退出此任務並獲得初始貢獻的退款。',
      yourContribution: '您的貢獻',
      crowdfunding: '眾籌',
      contributors: '貢獻者',
      refundInfo: '您將獲得初始貢獻的退款。眾籌貢獻將保留在任務中。',
      cancel: '取消',
      confirm: '退出並退款',
      exiting: '退出中...',
    },
    abandonQuest: {
      title: '放棄任務',
      description: '您即將放棄此任務。這將產生嚴重後果:',
      forfeitAmount: '沒收押金',
      depositRateReset: '新押金率',
      warning: '您的押金將被沒收,押金率將重置為50%。',
      typeConfirm: '輸入 CONFIRM 繼續',
      typeConfirmHint: '輸入大寫字母"CONFIRM"以啟用放棄按鈕',
      cancel: '取消',
      confirm: '放棄任務',
      abandoning: '放棄中...',
    },
    dailyCheckIn: {
      title: '每日打卡',
      day: '第',
      description: '記錄今天的進度',
      firstDayNote: '這是您的第1天基準。未來的對比將參考此記錄。',
      progress: '進度',
      target: '目標',
      days: '天',
      statusUpdate: '狀態更新',
      statusPlaceholder: '今天怎麼樣?有什麼挑戰或收穫?',
      photo: '進度照片',
      uploadPhoto: '點擊上傳照片',
      photoOptional: '可選但推薦',
      uploading: '上傳中',
      submit: '提交打卡',
      submitting: '提交中...',
      requireContent: '請添加狀態更新或照片',
      submitSuccess: '打卡提交成功!',
      submitError: '打卡提交失敗',
      fileTooLarge: '文件大小必須小於5MB',
    },
    visualComparison: {
      title: '視覺進度對比',
      day: '第',
      totalCheckIns: '總打卡次數',
      timeline: '完整時間線',
      autoGenerated: '自動生成的基準照片',
    },
    disputeResolution: {
      title: '爭議解決',
      subtitle: '社區驅動的公正系統',
      noDisputes: '暫無活躍爭議',
      questTitle: '任務',
      publisher: '發布者',
      warrior: '勇士',
      publisherArgument: '發布者論據',
      warriorArgument: '勇士論據',
      voteDistribution: '投票分佈',
      publisherVotes: '發布者',
      adminVotes: '管理員',
      communityVotes: '社區',
      voteForPublisher: '支持發布者',
      voteForWarrior: '支持勇士',
      votingClosed: '投票已關閉',
    },
    appealSubmission: {
      title: '提交申訴',
      description: '解釋為什麼您認為爭議應該以您的方式解決',
      yourArgument: '您的論據',
      argumentPlaceholder: '提供詳細的證據和理由...',
      minCharacters: '至少需要100個字符',
      submit: '提交申訴',
      submitting: '提交中...',
      argumentTooShort: '論據至少需要100個字符',
      submitSuccess: '申訴提交成功!',
      submitError: '申訴提交失敗',
      viewAppeal: '查看已提交的申訴',
      yourAppeal: '您的申訴',
      noAppeal: '尚未提交申訴',
    },
    introduction: {
      linkText: 'How it works? (運作規則)',
      title: 'Grit Bounty',
      subtitle: '將"如果當初"變為現實',
      coreMission: {
        title: '一、我們的核心使命',
        content:
          '如果你曾經有一個堅持的目標,但是沒有堅持下來,卻又想知道如果當時堅持下去會發生什麼樣的結果——就是現在,我們把它變成現實!',
      },
      useCases: {
        title: '二、無論你的想法多麼奇特',
        intro:
          '大多數人都有自己的想法跟創意,但往往因為各種原因沒能長時間堅持。現在,我們的勇士幫你實現:',
        lifestyle: '生活作息',
        lifestyleExample: '堅持每天5點起床。',
        health: '健康飲食',
        healthExample: '堅持一個月每天只吃蔬菜,或每天堅持吃1-2克維生素C。',
        exercise: '運動挑戰',
        exerciseExample: '每天跑步10公里,或徒步到某些地方。',
        social: '社交創意',
        socialExample: '每天堅持結交3個異性朋友。',
        enterprise: '企業推廣',
        enterpriseExample: '企業可以推廣新APP,收集用戶反饋,激勵用戶參與。',
        more: '更多可能',
        moreExample: '以及任何其他奇怪的事情。',
      },
      bountyMechanism: {
        title: '三、懸賞與運作機制',
        publishTitle: '發布任務',
        publishContent:
          '你只需要發布任務,並押注自己的信用貨幣(如100 ICP)。發布時需填寫執行人數、完成任務的總賞金,並立即向平台支付賞金。',
        crowdfundTitle: '眾人加碼',
        crowdfundContent:
          '吸引同樣想看到結果的同類人群,他們可以進入並進行打賞。當賞金積累到大家願意接任務的水平時,勇士可根據情況選擇接取。',
        acceptTitle: '勇士領命',
        acceptContent:
          '認為自己能堅持並做到這件有意義事情的勇士,可以領取任務並提交部分ICP作為抵押。',
        flexibleTitle: '自由設定',
        flexibleContent: '懸賞者可以自由增加勇士數量,可以是一個、兩個或更多。',
      },
      settlementRules: {
        title: '四、結算與費用說明',
        successTitle: '任務成功',
        successContent:
          '到期順利堅持下來,任務自動解鎖,賞金發放至勇士錢包,押金自動退回勇士賬戶。',
        unclaimedTitle: '任務未完成',
        unclaimedContent: '若任務未被領取,賞金與押金全部退回發布者。',
        defaultTitle: '違約賠付',
        defaultContent:
          '若任務被領取但勇士未完成,扣除勇士所有押金,賞金退回發布者。',
        feesTitle: '平台費用',
        feesSuccessLabel: '任務成功',
        feesSuccessContent: '平台抽取6%作為運營費用。',
        feesDefaultLabel: '任務違約(勇士未完成)',
        feesDefaultContent: '平台抽取勇士押金的6%,剩餘94%的押金全部給發布者。',
      },
      warriorCredit: {
        title: '五、勇士信用減免系統',
        intro: '我們通過階梯式押金制度鼓勵真正的勇士:',
        initialTitle: '初始門檻',
        initialContent: '從50%押金開始起步。',
        rewardTitle: '成功獎勵',
        rewardContent: '每成功完成一次任務,下次接單的押金比例減少3%。',
        capTitle: '誠信封頂',
        capContent:
          '持續循環直到押金降至2%(即成功完成16次任務後達到最低2%押金)。',
        penaltyTitle: '懲罰機制',
        penaltyContent:
          '如果中途放棄任務或爭議投票失敗,押金立即重置為50%並重新開始循環。',
      },
    },
    footer: {
      builtWith: '用',
      love: '愛',
      using: '構建,使用',
    },
  },
};
