import { useState } from 'react';
import { useLanguage } from '../hooks/useLanguage';
import { QuestImmutable } from '../backend';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { Calendar, TrendingUp } from 'lucide-react';

interface VisualComparisonProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  quest: QuestImmutable;
}

export default function VisualComparison({ open, onOpenChange, quest }: VisualComparisonProps) {
  const { t } = useLanguage();
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null);

  const checkIns = quest.dailyCheckIns;
  const firstCheckIn = checkIns[0];
  const latestCheckIn = checkIns[checkIns.length - 1];

  const formatDate = (timestamp: bigint) => {
    const date = new Date(Number(timestamp) / 1000000);
    return date.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
  };

  const getPhotoUrl = (photoUrl?: string) => {
    if (!photoUrl) return '/assets/generated/splash-bg.dim_1920x1080.png';
    return photoUrl;
  };

  const selectedCheckIn = selectedIndex !== null ? checkIns[selectedIndex] : null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-5xl border-neon-blue/30 bg-card/95 backdrop-blur max-h-[90vh]">
        <DialogHeader>
          <DialogTitle className="text-neon-blue flex items-center gap-2">
            <TrendingUp className="h-5 w-5" />
            {t('visualComparison.title')}
          </DialogTitle>
        </DialogHeader>

        <ScrollArea className="max-h-[calc(90vh-120px)]">
          <div className="space-y-6 p-4">
            {/* Quest Info */}
            <div>
              <h3 className="font-semibold text-lg mb-2">{quest.title}</h3>
              <p className="text-sm text-muted-foreground">
                {t('visualComparison.totalCheckIns')}: {checkIns.length} / {Number(quest.completionTarget)}
              </p>
            </div>

            <Separator />

            {/* Day 1 vs Now Comparison */}
            {checkIns.length > 0 && (
              <div className="grid md:grid-cols-2 gap-6">
                {/* Day 1 */}
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <Badge className="bg-green-500/20 text-green-400 border-green-500/30">
                      {t('visualComparison.day')} 1
                    </Badge>
                    <span className="text-xs text-muted-foreground flex items-center gap-1">
                      <Calendar className="h-3 w-3" />
                      {formatDate(firstCheckIn.timestamp)}
                    </span>
                  </div>
                  <div className="aspect-square rounded-lg overflow-hidden border-2 border-neon-cyan/30">
                    <img
                      src={getPhotoUrl(firstCheckIn.photoUrl)}
                      alt="Day 1"
                      className="w-full h-full object-cover"
                    />
                  </div>
                  {firstCheckIn.statusText && (
                    <div className="p-3 rounded-lg bg-card/50 border border-border">
                      <p className="text-sm">{firstCheckIn.statusText}</p>
                    </div>
                  )}
                  {!firstCheckIn.photoUrl && (
                    <p className="text-xs text-muted-foreground italic">
                      {t('visualComparison.autoGenerated')}
                    </p>
                  )}
                </div>

                {/* Current Day */}
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <Badge className="bg-neon-magenta/20 text-neon-magenta border-neon-magenta/30">
                      {t('visualComparison.day')} {checkIns.length}
                    </Badge>
                    <span className="text-xs text-muted-foreground flex items-center gap-1">
                      <Calendar className="h-3 w-3" />
                      {formatDate(latestCheckIn.timestamp)}
                    </span>
                  </div>
                  <div className="aspect-square rounded-lg overflow-hidden border-2 border-neon-magenta/30">
                    <img
                      src={getPhotoUrl(latestCheckIn.photoUrl)}
                      alt={`Day ${checkIns.length}`}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  {latestCheckIn.statusText && (
                    <div className="p-3 rounded-lg bg-card/50 border border-border">
                      <p className="text-sm">{latestCheckIn.statusText}</p>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Timeline */}
            {checkIns.length > 1 && (
              <>
                <Separator />
                <div className="space-y-3">
                  <h4 className="font-semibold text-sm text-neon-blue">
                    {t('visualComparison.timeline')}
                  </h4>
                  <div className="grid grid-cols-4 sm:grid-cols-6 md:grid-cols-8 gap-3">
                    {checkIns.map((checkIn, index) => (
                      <button
                        key={index}
                        onClick={() => setSelectedIndex(index)}
                        className={`relative aspect-square rounded-lg overflow-hidden border-2 transition-all hover:scale-105 ${
                          selectedIndex === index
                            ? 'border-neon-cyan ring-2 ring-neon-cyan/50'
                            : 'border-border hover:border-neon-cyan/50'
                        }`}
                      >
                        <img
                          src={getPhotoUrl(checkIn.photoUrl)}
                          alt={`Day ${checkIn.dayNumber}`}
                          className="w-full h-full object-cover"
                        />
                        <div className="absolute bottom-0 left-0 right-0 bg-black/70 text-white text-xs py-1 text-center">
                          D{Number(checkIn.dayNumber)}
                        </div>
                      </button>
                    ))}
                  </div>
                </div>
              </>
            )}

            {/* Selected Check-in Detail */}
            {selectedCheckIn && (
              <>
                <Separator />
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <h4 className="font-semibold text-sm text-neon-cyan">
                      {t('visualComparison.day')} {Number(selectedCheckIn.dayNumber)}
                    </h4>
                    <span className="text-xs text-muted-foreground flex items-center gap-1">
                      <Calendar className="h-3 w-3" />
                      {formatDate(selectedCheckIn.timestamp)}
                    </span>
                  </div>
                  <div className="max-w-md mx-auto">
                    <div className="aspect-square rounded-lg overflow-hidden border-2 border-neon-cyan/30">
                      <img
                        src={getPhotoUrl(selectedCheckIn.photoUrl)}
                        alt={`Day ${selectedCheckIn.dayNumber}`}
                        className="w-full h-full object-cover"
                      />
                    </div>
                    {selectedCheckIn.statusText && (
                      <div className="mt-3 p-3 rounded-lg bg-card/50 border border-border">
                        <p className="text-sm">{selectedCheckIn.statusText}</p>
                      </div>
                    )}
                  </div>
                </div>
              </>
            )}
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
