/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const QuestStatus = IDL.Variant({
  'pendingVerification' : IDL.Null,
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'disputed' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const CheckInRecord = IDL.Record({
  'photoUrl' : IDL.Opt(IDL.Text),
  'dayNumber' : IDL.Nat,
  'timestamp' : IDL.Int,
  'statusText' : IDL.Text,
});
export const QuestImmutable = IDL.Record({
  'status' : QuestStatus,
  'completedAt' : IDL.Opt(IDL.Int),
  'depositAmount' : IDL.Nat64,
  'title' : IDL.Text,
  'hypeCount' : IDL.Nat,
  'difficulty' : Difficulty,
  'createdAt' : IDL.Int,
  'publisherId' : IDL.Principal,
  'dailyCheckIns' : IDL.Vec(CheckInRecord),
  'description' : IDL.Text,
  'crowdfundingContributions' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat64)),
  'rewardPool' : IDL.Nat64,
  'warriorId' : IDL.Opt(IDL.Principal),
  'questId' : IDL.Nat,
  'participantCount' : IDL.Nat,
  'completionTarget' : IDL.Nat,
  'acceptedAt' : IDL.Opt(IDL.Int),
  'currentStreak' : IDL.Nat,
  'depositRate' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'totalEarned' : IDL.Nat64,
  'successfulQuests' : IDL.Nat,
  'totalDeposited' : IDL.Nat64,
  'depositRate' : IDL.Nat,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'success' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
  'taskPayment' : IDL.Null,
  'taskDeduction' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'from' : IDL.Principal,
  'amountE8' : IDL.Nat64,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'abandonQuest' : IDL.Func([IDL.Nat], [], []),
  'acceptQuest' : IDL.Func([IDL.Nat], [], []),
  'addToPot' : IDL.Func([IDL.Nat, IDL.Nat64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createABQuest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat64,
        Difficulty,
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat, IDL.Nat],
      [],
    ),
  'createQuest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat64, Difficulty, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'deleteQuest' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'exitQuest' : IDL.Func([IDL.Nat], [], []),
  'getActiveQuests' : IDL.Func(
      [IDL.Opt(Difficulty)],
      [IDL.Vec(QuestImmutable)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAcceptedQuests' : IDL.Func([], [IDL.Vec(QuestImmutable)], ['query']),
  'getMyPostedBounties' : IDL.Func([], [IDL.Vec(QuestImmutable)], ['query']),
  'getTransactionsView' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Transaction))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCompletion' : IDL.Func([IDL.Nat], [], []),
  'submitDailyCheckIn' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const QuestStatus = IDL.Variant({
    'pendingVerification' : IDL.Null,
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'disputed' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const CheckInRecord = IDL.Record({
    'photoUrl' : IDL.Opt(IDL.Text),
    'dayNumber' : IDL.Nat,
    'timestamp' : IDL.Int,
    'statusText' : IDL.Text,
  });
  const QuestImmutable = IDL.Record({
    'status' : QuestStatus,
    'completedAt' : IDL.Opt(IDL.Int),
    'depositAmount' : IDL.Nat64,
    'title' : IDL.Text,
    'hypeCount' : IDL.Nat,
    'difficulty' : Difficulty,
    'createdAt' : IDL.Int,
    'publisherId' : IDL.Principal,
    'dailyCheckIns' : IDL.Vec(CheckInRecord),
    'description' : IDL.Text,
    'crowdfundingContributions' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat64)),
    'rewardPool' : IDL.Nat64,
    'warriorId' : IDL.Opt(IDL.Principal),
    'questId' : IDL.Nat,
    'participantCount' : IDL.Nat,
    'completionTarget' : IDL.Nat,
    'acceptedAt' : IDL.Opt(IDL.Int),
    'currentStreak' : IDL.Nat,
    'depositRate' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'totalEarned' : IDL.Nat64,
    'successfulQuests' : IDL.Nat,
    'totalDeposited' : IDL.Nat64,
    'depositRate' : IDL.Nat,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'success' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
    'taskPayment' : IDL.Null,
    'taskDeduction' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'status' : TransactionStatus,
    'transactionType' : TransactionType,
    'from' : IDL.Principal,
    'amountE8' : IDL.Nat64,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'abandonQuest' : IDL.Func([IDL.Nat], [], []),
    'acceptQuest' : IDL.Func([IDL.Nat], [], []),
    'addToPot' : IDL.Func([IDL.Nat, IDL.Nat64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createABQuest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat64,
          Difficulty,
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat, IDL.Nat],
        [],
      ),
    'createQuest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat64, Difficulty, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'deleteQuest' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'exitQuest' : IDL.Func([IDL.Nat], [], []),
    'getActiveQuests' : IDL.Func(
        [IDL.Opt(Difficulty)],
        [IDL.Vec(QuestImmutable)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAcceptedQuests' : IDL.Func([], [IDL.Vec(QuestImmutable)], ['query']),
    'getMyPostedBounties' : IDL.Func([], [IDL.Vec(QuestImmutable)], ['query']),
    'getTransactionsView' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Transaction))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCompletion' : IDL.Func([IDL.Nat], [], []),
    'submitDailyCheckIn' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };