/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BountyContribution {
  'contributorId' : Principal,
  'amountCents' : bigint,
  'timestamp' : bigint,
}
export type Cents = bigint;
export interface CheckInRecord {
  'photoUrl' : [] | [string],
  'dayNumber' : bigint,
  'timestamp' : bigint,
  'statusText' : string,
}
export interface CreateQuestRequest {
  'title' : string,
  'difficulty' : Difficulty,
  'rewardCents' : Cents,
  'description' : string,
  'rewardUSD' : USD,
  'participantCount' : [] | [bigint],
}
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface QuestImmutable {
  'status' : QuestStatus,
  'completedAt' : [] | [bigint],
  'depositAmount' : bigint,
  'reward' : bigint,
  'title' : string,
  'hypeCount' : bigint,
  'difficulty' : Difficulty,
  'createdAt' : bigint,
  'bountyContributions' : Array<BountyContribution>,
  'publisherId' : Principal,
  'dailyCheckIns' : Array<CheckInRecord>,
  'description' : string,
  'originalBountyAmountCents' : bigint,
  'warriorId' : [] | [Principal],
  'questId' : bigint,
  'participantCount' : bigint,
  'completionTarget' : bigint,
  'acceptedAt' : [] | [bigint],
  'currentStreak' : bigint,
  'depositRate' : bigint,
}
export type QuestStatus = { 'pendingVerification' : null } |
  { 'active' : null } |
  { 'cancelled' : null } |
  { 'disputed' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface RechargeDialogRequest {
  'amountCents' : Cents,
  'amountUSD' : USD,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Transaction {
  'id' : bigint,
  'to' : Principal,
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'from' : Principal,
  'amountCents' : bigint,
  'timestamp' : bigint,
}
export type TransactionStatus = { 'pending' : null } |
  { 'success' : null } |
  { 'failed' : null };
export type TransactionType = { 'deposit' : null } |
  { 'serviceFee' : null } |
  { 'withdrawal' : null } |
  { 'taskPayment' : null } |
  { 'taskDeduction' : null } |
  { 'bountyContribution' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type USD = bigint;
export interface UserProfile {
  'name' : string,
  'totalEarned' : bigint,
  'successfulQuests' : bigint,
  'totalDeposited' : bigint,
  'depositRate' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'abandonQuest' : ActorMethod<[bigint], undefined>,
  'acceptQuest' : ActorMethod<[bigint], undefined>,
  'addToBounty' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createABQuest' : ActorMethod<
    [string, string, string, string, bigint, Difficulty, [] | [bigint]],
    [bigint, bigint]
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createQuest' : ActorMethod<[CreateQuestRequest], bigint>,
  'createStripeCheckoutSession' : ActorMethod<
    [RechargeDialogRequest, string, string],
    string
  >,
  'deleteQuest' : ActorMethod<[bigint], string>,
  'exitQuest' : ActorMethod<[bigint], undefined>,
  'getActiveQuests' : ActorMethod<[[] | [Difficulty]], Array<QuestImmutable>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAcceptedQuests' : ActorMethod<[], Array<QuestImmutable>>,
  'getMyPostedBounties' : ActorMethod<[], Array<QuestImmutable>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTransactionsView' : ActorMethod<[], Array<[bigint, Transaction]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserWalletBalance' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'recordSuccessfulRecharge' : ActorMethod<
    [bigint, Cents, Principal],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitCompletion' : ActorMethod<[bigint], undefined>,
  'submitDailyCheckIn' : ActorMethod<
    [bigint, string, [] | [string]],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];