/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Cents = IDL.Nat;
export const USD = IDL.Nat;
export const CreateQuestRequest = IDL.Record({
  'title' : IDL.Text,
  'difficulty' : Difficulty,
  'rewardCents' : Cents,
  'description' : IDL.Text,
  'rewardUSD' : USD,
  'participantCount' : IDL.Opt(IDL.Nat),
});
export const RechargeDialogRequest = IDL.Record({
  'amountCents' : Cents,
  'amountUSD' : USD,
});
export const QuestStatus = IDL.Variant({
  'pendingVerification' : IDL.Null,
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'disputed' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const BountyContribution = IDL.Record({
  'contributorId' : IDL.Principal,
  'amountCents' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const CheckInRecord = IDL.Record({
  'photoUrl' : IDL.Opt(IDL.Text),
  'dayNumber' : IDL.Nat,
  'timestamp' : IDL.Int,
  'statusText' : IDL.Text,
});
export const QuestImmutable = IDL.Record({
  'status' : QuestStatus,
  'completedAt' : IDL.Opt(IDL.Int),
  'depositAmount' : IDL.Nat,
  'reward' : IDL.Nat,
  'title' : IDL.Text,
  'hypeCount' : IDL.Nat,
  'difficulty' : Difficulty,
  'createdAt' : IDL.Int,
  'bountyContributions' : IDL.Vec(BountyContribution),
  'publisherId' : IDL.Principal,
  'dailyCheckIns' : IDL.Vec(CheckInRecord),
  'description' : IDL.Text,
  'originalBountyAmountCents' : IDL.Nat,
  'warriorId' : IDL.Opt(IDL.Principal),
  'questId' : IDL.Nat,
  'participantCount' : IDL.Nat,
  'completionTarget' : IDL.Nat,
  'acceptedAt' : IDL.Opt(IDL.Int),
  'currentStreak' : IDL.Nat,
  'depositRate' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'totalEarned' : IDL.Nat,
  'successfulQuests' : IDL.Nat,
  'totalDeposited' : IDL.Nat,
  'depositRate' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'success' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'deposit' : IDL.Null,
  'serviceFee' : IDL.Null,
  'withdrawal' : IDL.Null,
  'taskPayment' : IDL.Null,
  'taskDeduction' : IDL.Null,
  'bountyContribution' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'from' : IDL.Principal,
  'amountCents' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'abandonQuest' : IDL.Func([IDL.Nat], [], []),
  'acceptQuest' : IDL.Func([IDL.Nat], [], []),
  'addToBounty' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createABQuest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        Difficulty,
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat, IDL.Nat],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createQuest' : IDL.Func([CreateQuestRequest], [IDL.Nat], []),
  'createStripeCheckoutSession' : IDL.Func(
      [RechargeDialogRequest, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteQuest' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'exitQuest' : IDL.Func([IDL.Nat], [], []),
  'getActiveQuests' : IDL.Func(
      [IDL.Opt(Difficulty)],
      [IDL.Vec(QuestImmutable)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAcceptedQuests' : IDL.Func([], [IDL.Vec(QuestImmutable)], ['query']),
  'getMyPostedBounties' : IDL.Func([], [IDL.Vec(QuestImmutable)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTransactionsView' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Transaction))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'recordSuccessfulRecharge' : IDL.Func(
      [IDL.Nat, Cents, IDL.Principal],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitCompletion' : IDL.Func([IDL.Nat], [], []),
  'submitDailyCheckIn' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Cents = IDL.Nat;
  const USD = IDL.Nat;
  const CreateQuestRequest = IDL.Record({
    'title' : IDL.Text,
    'difficulty' : Difficulty,
    'rewardCents' : Cents,
    'description' : IDL.Text,
    'rewardUSD' : USD,
    'participantCount' : IDL.Opt(IDL.Nat),
  });
  const RechargeDialogRequest = IDL.Record({
    'amountCents' : Cents,
    'amountUSD' : USD,
  });
  const QuestStatus = IDL.Variant({
    'pendingVerification' : IDL.Null,
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'disputed' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const BountyContribution = IDL.Record({
    'contributorId' : IDL.Principal,
    'amountCents' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const CheckInRecord = IDL.Record({
    'photoUrl' : IDL.Opt(IDL.Text),
    'dayNumber' : IDL.Nat,
    'timestamp' : IDL.Int,
    'statusText' : IDL.Text,
  });
  const QuestImmutable = IDL.Record({
    'status' : QuestStatus,
    'completedAt' : IDL.Opt(IDL.Int),
    'depositAmount' : IDL.Nat,
    'reward' : IDL.Nat,
    'title' : IDL.Text,
    'hypeCount' : IDL.Nat,
    'difficulty' : Difficulty,
    'createdAt' : IDL.Int,
    'bountyContributions' : IDL.Vec(BountyContribution),
    'publisherId' : IDL.Principal,
    'dailyCheckIns' : IDL.Vec(CheckInRecord),
    'description' : IDL.Text,
    'originalBountyAmountCents' : IDL.Nat,
    'warriorId' : IDL.Opt(IDL.Principal),
    'questId' : IDL.Nat,
    'participantCount' : IDL.Nat,
    'completionTarget' : IDL.Nat,
    'acceptedAt' : IDL.Opt(IDL.Int),
    'currentStreak' : IDL.Nat,
    'depositRate' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'totalEarned' : IDL.Nat,
    'successfulQuests' : IDL.Nat,
    'totalDeposited' : IDL.Nat,
    'depositRate' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'success' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'deposit' : IDL.Null,
    'serviceFee' : IDL.Null,
    'withdrawal' : IDL.Null,
    'taskPayment' : IDL.Null,
    'taskDeduction' : IDL.Null,
    'bountyContribution' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'status' : TransactionStatus,
    'transactionType' : TransactionType,
    'from' : IDL.Principal,
    'amountCents' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'abandonQuest' : IDL.Func([IDL.Nat], [], []),
    'acceptQuest' : IDL.Func([IDL.Nat], [], []),
    'addToBounty' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createABQuest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          Difficulty,
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat, IDL.Nat],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createQuest' : IDL.Func([CreateQuestRequest], [IDL.Nat], []),
    'createStripeCheckoutSession' : IDL.Func(
        [RechargeDialogRequest, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteQuest' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'exitQuest' : IDL.Func([IDL.Nat], [], []),
    'getActiveQuests' : IDL.Func(
        [IDL.Opt(Difficulty)],
        [IDL.Vec(QuestImmutable)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAcceptedQuests' : IDL.Func([], [IDL.Vec(QuestImmutable)], ['query']),
    'getMyPostedBounties' : IDL.Func([], [IDL.Vec(QuestImmutable)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTransactionsView' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Transaction))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'recordSuccessfulRecharge' : IDL.Func(
        [IDL.Nat, Cents, IDL.Principal],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitCompletion' : IDL.Func([IDL.Nat], [], []),
    'submitDailyCheckIn' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };